services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile.dev
    container_name: auth-dev
    ports:
      - "4444:4444"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    container_name: backend-dev
    ports:
      - "3333:3333"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: app_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
