packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@prisma/engines": false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  sharp: false
  unrs-resolver: false
  wd: set this to true or false
onlyBuiltDependencies:
  - "prisma"
  - "esbuild"
  - "@swc/core"
