FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json ./apps/backend/package.json
COPY packages/common/package.json ./packages/common/package.json

RUN pnpm install

COPY . .

EXPOSE 3333

CMD ["sh", "-c", "cd apps/backend && pnpm dev"]
