/**
 * Tokens oficiais de DI do módulo Authentication V2.
 *
 * Use estes tokens em vez de classes concretas para manter o domínio desacoplado
 * e permitir trocar providers sem alterar use cases/controllers.
 */
export const AUTH_DI_TOKENS = {
  // Prisma / Database
  // PRISMA_CLIENT: "AUTH.PRISMA_CLIENT",

  // Repositories
  USER_REPOSITORY: "AUTH.USER_REPOSITORY",
  SESSION_REPOSITORY: "AUTH.SESSION_REPOSITORY",
  SESSION_CACHE_REPOSITORY: "AUTH.SESSION_CACHE_REPOSITORY",
  OTP_REPOSITORY: "AUTH.OTP_REPOSITORY",
  MAGIC_LINK_REPOSITORY: "AUTH.MAGIC_LINK_REPOSITORY",
  EMAIL_VERIFICATION_REPOSITORY: "AUTH.EMAIL_VERIFICATION_REPOSITORY",
  ACCOUNT_REPOSITORY: "AUTH.ACCOUNT_REPOSITORY",
  AUDIT_LOG_REPOSITORY: "AUTH.AUDIT_LOG_REPOSITORY",

  // // Crypto / Tokens
  // PASSWORD_HASHER: "AUTH.PASSWORD_HASHER",
  // PASSWORD_COMPARER: "AUTH.PASSWORD_COMPARER",
  // SESSION_TOKEN_SERVICE: "AUTH.SESSION_TOKEN_SERVICE",
  // OPAQUE_TOKEN_GENERATOR: "AUTH.OPAQUE_TOKEN_GENERATOR",
  // HASH_GENERATOR: "AUTH.HASH_GENERATOR",

  // Use Cases
  REGISTER_USE_CASE: "AUTH.REGISTER_USE_CASE",
  CREATE_SESSION_USE_CASE: "AUTH.CREATE_SESSION_USE_CASE",
  RESOLVE_SESSION_USE_CASE: "AUTH.RESOLVE_SESSION_USE_CASE",
  REFRESH_SESSION_USE_CASE: "AUTH.REFRESH_SESSION_USE_CASE",
  LOGOUT_USE_CASE: "AUTH.LOGOUT_USE_CASE",
  REVOKE_ALL_SESSIONS_USE_CASE: "AUTH.REVOKE_ALL_SESSIONS_USE_CASE",

  // Controllers
  REGISTER_CONTROLLER: "AUTH.REGISTER_CONTROLLER",
  LOGIN_CONTROLLER: "AUTH.LOGIN_CONTROLLER",
  LOGOUT_CONTROLLER: "AUTH.LOGOUT_CONTROLLER",
  ME_CONTROLLER: "AUTH.ME_CONTROLLER",
  REFRESH_SESSION_CONTROLLER: "AUTH.REFRESH_SESSION_CONTROLLER",
} as const;

export type AuthDiToken = (typeof AUTH_DI_TOKENS)[keyof typeof AUTH_DI_TOKENS];
