export const SERVICE_CONSTANTS = {
  BCRYPT_HASHER_SERVICE: "BCRYPT_HASHER_SERVICE",
  BCRYPT_COMPARER_SERVICE: "BCRYPT_COMPARER_SERVICE",
  BCRYPT_GENERATOR_SERVICE: "BCRYPT_GENERATOR_SERVICE",
  JWT_ENCRYPTER_SERVICE: "JWT_ENCRYPTER_SERVICE",
};
