export const SERVICE_BACKEND_CONSTANTS = {
  AUTH_LOGIN_SERVICE_CLIENT: "AUTH_LOGIN_SERVICE_CLIENT",
  AUTH_LOGOUT_CLIENT: "AUTH_LOGOUT_CLIENT",
  AUTH_REFRESH_CLIENT: "AUTH_REFRESH_CLIENT",
  AUTH_VALIDATE_CLIENT: "AUTH_VALIDATE_CLIENT",
  AUTH_ME_CLIENT: "AUTH_ME_CLIENT",
};
