export const DI_REPOSITORY = {
  PRISMA_OTP_CODE_REPOSITORY: "PRISMA_OTP_CODE_REPOSITORY",
  PRISMA_USER_REPOSITORY: "PRISMA_USER_REPOSITORY",
  PRISMA_AUDIT_LOG_REPOSITORY: "PRISMA_AUDIT_LOG_REPOSITORY",
  PRISMA_SESSION_REPOSITORY: "PRISMA_SESSION_REPOSITORY",
  PRISMA_MAGIC_LINK_REPOSITORY: "PRISMA_MAGIC_LINK_REPOSITORY",
  PRISMA_EMAIL_VERIFICATION_REPOSITORY: "PRISMA_EMAIL_VERIFICATION_REPOSITORY",
  PRISMA_ACCOUNT_REPOSITORY: "PRISMA_ACCOUNT_REPOSITORY",
};
