export const REPOSITORY_CONSTANTS = {
  PRISMA_OTP_REPOSITORY: "PRISMA_OTP_REPOSITORY",
  PRISMA_USER_REPOSITORY: "PRISMA_USER_REPOSITORY",
  PRISMA_SESSION_REPOSITORY: "PRISMA_SESSION_REPOSITORY",
  PRISMA_TOKEN_REPOSITORY: "PRISMA_TOKEN_REPOSITORY",
  REDIS_SESSION_CACHE_REPOSITORY: "REDIS_SESSION_CACHE_REPOSITORY",
};
