// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type AccountDto = {
  id: string;
  userId: string;
  providerAccountId: string;
  provider: string;
  email: string;
  refreshToken: string | null;
  accessToken: string | null;
  expiresAt: number | null;
  createdAt: Date;
  updatedAt: Date | null;
  deletedAt: Date | null;
};

// DTOs for creating, updating, and projecting Account entities
export type AccountCreateDto = Omit<
  AccountDto,
  "id" | "createdAt" | "updatedAt" | "deletedAt"
>;
// For updates, all fields are optional except for the id
export type AccountUpdateDto = Partial<AccountDto>;

// Projection DTO for returning only specific fields of the Account entity
export type AccountProjectionDto = Pick<
  AccountDto,
  "id" | "userId" | "providerAccountId" | "provider" | "email"
>;
