// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type AuditLogDto = {
  id: string;
  userId: string | null;
  tenantId: string | null;
  organizationId: string | null;
  action: string;
  resource: string;
  resource_id: string;
  ipAddress: string | null;
  userAgent: string | null;
  metadata: Record<string, string | number | boolean | null>;
  createdAt: Date;
};

// DTOs for creating, updating, and projecting AuditLog entities
export type AuditLogCreateDto = Omit<AuditLogDto, "id" | "createdAt">;
// For updates, all fields are optional except for the id
export type AuditLogUpdateDto = Partial<AuditLogDto>;

// Projection DTO for returning only specific fields of the AuditLog entity
export type AuditLogProjectionDto = Pick<
  AuditLogDto,
  "id" | "userId" | "action" | "resource" | "createdAt"
>;
