// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type EmailVerificationTokenDto = {
  id: string;
  userId: string;
  tokenHash: string;
  expiresAt: string;
  usedAt: string | null;
  createdAt: string;
  deletedAt: string | null;
};

// DTOs for creating, updating, and projecting EmailVerificationToken entities
export type EmailVerificationTokenCreateDto = Omit<
  EmailVerificationTokenDto,
  "id" | "createdAt" | "updatedAt" | "deletedAt"
>;
// For updates, all fields are optional except for the id
export type EmailVerificationTokenUpdateDto = Partial<EmailVerificationTokenDto>;

// Projection DTO for returning only specific fields of the EmailVerificationToken entity
export type EmailVerificationTokenProjectionDto = Pick<
  EmailVerificationTokenDto,
  "id" | "userId" | "tokenHash" | "expiresAt" | "usedAt"
>;
