import { UserProjectionDto } from "./user.dto";

// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type MagicLinkTokenDto = {
  id: string;
  email: string;
  tokenHash: string;
  ipAddress: string;
  userAgent: string;
  expiresAt: string;
  usedAt: string | null;
  createdAt: string;
  deletedAt: string | null;
};

// DTOs for creating, updating, and projecting MagicLink entities
export type MagicLinkTokenCreateDto = Omit<
  MagicLinkTokenDto,
  "id" | "createdAt" | "updatedAt" | "deletedAt"
>;
// For updates, all fields are optional except for the id
export type MagicLinkTokenUpdateDto = Partial<MagicLinkTokenDto>;

// Projection DTO for returning only specific fields of the MagicLink entity
export type MagicLinkTokenProjectionDto = Pick<
  MagicLinkTokenDto,
  "id" | "email" | "tokenHash" | "expiresAt" | "usedAt"
>;

export type MagicLinkTokenUserProjectionDto = {
  tokenHash: string;
  expiresAt: string;
  user: UserProjectionDto;
};
