// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type MagicLinkDto = {
  id: string;
  email: string;
  tokenHash: string;
  ipAddress: string;
  userAgent: string;
  expiresAt: string;
  usedAt: string | null;
  createdAt: string;
  deletedAt: string | null;
};

// DTOs for creating, updating, and projecting MagicLink entities
export type MagicLinkCreateDto = Omit<
  MagicLinkDto,
  "id" | "createdAt" | "updatedAt" | "deletedAt"
>;
// For updates, all fields are optional except for the id
export type MagicLinkUpdateDto = Partial<MagicLinkDto>;

// Projection DTO for returning only specific fields of the MagicLink entity
export type MagicLinkProjectionDto = Pick<
  MagicLinkDto,
  "id" | "email" | "tokenHash" | "expiresAt" | "usedAt"
>;
