// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type OtpCodeDto = {
  id: string;
  email: string;
  codeHash: string;
  purpose: string;
  attempts: number;
  maxAttempts: number;
  ipAddress: string | null;
  userAgent: string | null;
  expiredAt: string;
  usedAt: string | null;
  createdAt: string;
  deletedAt: string | null;
};

// DTOs for creating, updating, and projecting OtpCode entities
export type OtpCodeCreateDto = Omit<
  OtpCodeDto,
  "id" | "createdAt" | "updatedAt" | "deletedAt"
>;
// For updates, all fields are optional except for the id
export type OtpCodeUpdateDto = Partial<OtpCodeDto>;

// Projection DTO for returning only specific fields of the OtpCode entity
export type OtpCodeProjectionDto = Pick<
  OtpCodeDto,
  | "id"
  | "email"
  | "codeHash"
  | "purpose"
  | "attempts"
  | "maxAttempts"
  | "expiredAt"
  | "usedAt"
>;
