// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type SessionDto = {
  id: string;
  userId: string;
  sessionToken: string;
  expires: string;
  ipAddress: string | null;
  userAgent: string | null;
  createdAt: string;
  updatedAt: string | null;
  deletedAt: string | null;
};

// DTOs for creating, updating, and projecting Session entities
export type SessionCreateDto = Omit<
  SessionDto,
  "id" | "createdAt" | "updatedAt" | "deletedAt"
>;
// For updates, all fields are optional except for the id
export type SessionUpdateDto = Partial<SessionDto>;

// Projection DTO for returning only specific fields of the Session entity
export type SessionProjectionDto = Pick<
  SessionDto,
  "id" | "userId" | "sessionToken" | "expires"
>;
