// This file was auto-generated by OpenAI's code generation tool. Do not edit this file directly. Instead, edit the source files and regenerate this file.
export type UserDto = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  passwordHash: string;
  emailVerified: string | null;
  createdAt: string;
  updatedAt: string | null;
  deletedAt: string | null;
};

// DTOs for creating, updating, and projecting User entities
export type UserCreateDto = Omit<UserDto, "id" | "createdAt" | "updatedAt" | "deletedAt">;
// For updates, all fields are optional except for the id
export type UserUpdateDto = Partial<UserDto>;

// Projection DTO for returning only specific fields of the User entity
export type UserProjectionDto = Pick<
  UserDto,
  "id" | "email" | "firstName" | "lastName" | "emailVerified"
>;
